WebApplication1/Models/Domain/BlogPost.cs
namespace WebApplication1.Models.Domain
{
    public class BlogPost
    {
        public Guid Id { get; set; }
        public string Handing { get; set;}
        public string PageTitle { get; set; }
        public string Content{ get; set; }
        public string ShortDescription { get; set; }
        public string FeaturedImageUrl { get; set; }
        public string UrlHandle { get; set; }
        public string Author { get; set; }
        public DateTime PublishedDate { get; set; }
        public bool Visiable { get; set; }
        public int TagId{ get; set; }      
        public Tag? Tag { get; set; }
    }
}

WebApplication1/Models/Domain/Tag.cs
using System.Linq.Expressions;

namespace WebApplication1.Models.Domain
{
    public class Tag
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }

        public ICollection<BlogPost> blogPosts { get; set; }
    }
}

WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/ViewModals/AddBlogPostRequest.cs
namespace WebApplication1.Models.ViewModals
{
	public class AddBlogPostRequest
	{
        public Guid Id { get; set; }
        public string Heading { get; set; }
        public string PageTitle { get; set; }
        public string  Content { get; set; }
        public string  ShortDescription { get; set; }
        public string  FeaturedImageUrl { get; set; }
        public string  UrlHandle { get; set; }
        public DateTime PoblishedDate { get; set; }
        public string Author { get; set; }
        public bool Visible { get; set; }
        public int TagId { get; set; }
    }
}

WebApplication1/Models/ViewModals/AddTagRequest.cs
namespace WebApplication1.Models.ViewModals
{
    public class AddTagRequest
    {
        public string Name { get; set; }
        public string DisplayName { get; set; }
    }
}

WebApplication1/Controllers/AdminTagsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebApplication1.Data;
using WebApplication1.Models.ViewModals;

namespace WebApplication1.Controllers
{
    public class AdminTagsController : Controller
    {
        private readonly BloggieDbContext bloggieDbContext;

        public AdminTagsController(BloggieDbContext bloggieDbContext) 
        {
            this.bloggieDbContext = bloggieDbContext;
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ActionName("Add")]
        public IActionResult Add(AddTagRequest addTagReauest) 
        {
            var tag = new Models.Domain.Tag
            {
                Name = addTagReauest.Name,
                DisplayName = addTagReauest.DisplayName
            };
            bloggieDbContext.Tags.Add(tag);
            return View("Add");
        }

        
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Data;
using WebApplication1.Models;
using WebApplication1.Models.Domain;
using Tag = WebApplication1.Models.Domain.Tag;
using WebApplication1.Models.ViewModals;
using Microsoft.AspNetCore.Components.Web;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly BloggieDbContext bloggieDbContext;
        private readonly List<BlogPost> blogPosts;
        private readonly List<Tag> tags;


        public HomeController(BloggieDbContext bloggieDbContext)
        {
            this.bloggieDbContext = bloggieDbContext;
            this.blogPosts = new List<BlogPost>();
            this.tags = new List<Tag>();
        }
        [HttpGet]
        public IActionResult Index()
        {
            var tag = bloggieDbContext.Tags.ToList();
            ViewBag.Tag = tag;
            var blogPost = bloggieDbContext.BlogPosts.ToList();
			ViewBag.blogPost = blogPost;
			return View(new AddBlogPostRequest());
        }
        [HttpPost]
		public IActionResult Index(AddBlogPostRequest addBlogPostRequest)
        {
            if(ModelState.IsValid)
            {
                var blogPost = new BlogPost
                {
                    Id = Guid.NewGuid(),
                    Handing = addBlogPostRequest.Heading,
                    PageTitle = addBlogPostRequest.PageTitle,
                    Content = addBlogPostRequest.Content,
                    ShortDescription = addBlogPostRequest.ShortDescription,
                    FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                    UrlHandle = addBlogPostRequest.UrlHandle,
                    PublishedDate = addBlogPostRequest.PoblishedDate,
                    Author = addBlogPostRequest.Author,
                    Visiable = addBlogPostRequest.Visible,
                    TagId = addBlogPostRequest.TagId
                };
                bloggieDbContext.BlogPosts.Add(blogPost);
                bloggieDbContext.SaveChanges();
            }
            ViewBag.BlogPost = bloggieDbContext.BlogPosts.ToList();
            return View(addBlogPostRequest);
        }

		public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/AdminTags/Add.cshtml
@model WebApplication1.Models.ViewModals.AddTagRequest
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div>
    <h1>Add new tag - Admin Functionality</h1>
</div>
<div>
    <form method="post">
        <div class="mr-3">
            <label class="form-label">Name</label>
            <input type="text" class="form-control" id="name" asp-for="Name">
        </div>
        <div class="mr-3">
            <label class="form-label">Display Name</label>
            <input type="text" class="form-control" id="displayName" asp-for="DisplayName">
        </div>
        <div class="mr-3">
            <button type="submit" class="btn btn-dark">Submit</button>
        </div>
    </form>
</div>

WebApplication1/Views/Home/Delete.cshtml
@page
@model WebApplication1.Views.Home.DeleteModel
@{
}

WebApplication1/Views/Home/Index.cshtml
@model WebApplication1.Models.ViewModals.AddTagRequest
<h4>Теги</h4>
<div>
	@if (ViewBag.Tag != null)
	{
		foreach(var tag in ViewBag.Tag)
		{
			if (tag != null)
			{
				<button class="btn tag-button" data-tag-id = @tag.Name>@tag.Name</button>
			}
		}
	}
</div>
<div>
	<div>
		<h5>
		</h5>
			<form method = "post">
			<div>
				<label class = "form-label">Заголовок</label>
				<input type="text" class = "form-control" id="blogPostHeading" name="Heading" />
			</div>
			<div>
				<label class="form-label">Название страницы</label>
				<input type="text" class="form-control" id="blogPostTitle" name="PageTitle" />
			</div>
			<div>
				<label class="form-label">Краткое описание</label>
				<input type="text" class="form-control" id="blogPostShortDescription" name="ShortDescription" />
			</div>
			<div>
				<label class="form-label">Краткое описание</label>
				<input type="text" class="form-control" id="blogPostShortDescription" name="ShortDescription" />
			</div>
			<div>
				<label class="form-label">URL изображение</label>
				<input type="text" class="form-control" id="blogPostFeaturedImageUrl" name="FeaturedImageUrl" />
			</div>
			<div>
				<label class="form-label">Контент</label>
				<input type="text" class="form-control" id="blogPostContent" name="Content" />
			</div>
			<div>
				<label class="form-label">URL Handle</label>
				<input type="text" class="form-control" id="blogPostUrlHandle" name="UrlHandle" />
			</div>
			<div>
				<label class="form-label">Дата публикации</label>
				<input type="date" class="form-control" id="blogPostPublishedDate" name="PublishedDate" />
			</div>
			<div>
				<label class="form-label">Автор</label>
				<input type="text" class="form-control" id="blogPostAuthor" name="Author" />
			</div>
			<div>
				<label class="form-label">Номер тега</label>
				<input type="text" class="form-control" id="blogPostTagId" name="TagId" />
			</div>
			<div>
				<button type="submit" class="btn btn-dark">Сохранить</button>
				<button type="button" class="btn btnDl" id="resetBtn">Сбросить</button>
			</div>
			</form>		
	</div>
</div>
<table id="dataTable" style="width:100%">
	<thead>
		<th>Заголовок</th>
		<th>Название страницы</th>
		<th>Краткое описание</th>
		<th>Url изображение</th>
		<th>Контент</th>
		<th>Url handle</th>
		<th>Дата публикации</th>
		<th>Автор</th>
		<th>Tag</th>
	</thead>
	<tbody>
		@foreach (var blogPost in ViewBag.BlogPost)
		{
			<tr data-rowid="@blogPost.Id">
				<td>@blogPost.Heading</td>
				<td>@blogPost.PageTitle</td>
				<td>@blogPost.ShortDescription</td>
				<td>@blogPost.FeaturedImageUrl</td>
				<td>@blogPost.Content</td>
				<td>@blogPost.UrlHandle</td>
				<td>@blogPost.PublishedDate</td>
				<td>@blogPost.Author</td>
				<td>@blogPost.TagId</td>
			</tr>
			<td>
				<a class="btnDl btn" href="/Delete?id=@blogPost.id">Удалить</a>
				<a class="btnemail btn" href="/Edit?id=@blogPost.id">Изменить</a>
				<a class="btnDl btn" href="/Details?id=@blogPost.id">Детали</a>
			</td>
		}
	</tbody>
</table>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <meta charset="utf-8" /> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /> 
    <title>@ViewData["Title"] - WebApplication3</title> 
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> 
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/materialize.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/tooplate.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication3.styles.css" asp-append-version="true" /> 
</head> 
<body> 
    <header> 
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3"> 
            <div class="container-fluid"> 
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication3</a> 
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" 
                        aria-expanded="false" aria-label="Toggle navigation"> 
                    <span class="navbar-toggler-icon"></span> 
                </button> 
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"> 
                    <ul class="navbar-nav flex-grow-1"> 
                        <li class="nav-item"> 
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a> 
                        </li> 
                        <li class="nav-item"> 
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> 
                        </li> 
                            <li class="nav-item dropdown"> 
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                                    Admin 
                                </a> 
                                <ul class="dropdown-menu"> 
                                    <li><a class="dropdown-item"  asp-area="" asp-controller="AdminTags" asp-action="Add">Add Tag</a></li> 
                                    

                                </ul> 
                            </li> 
                            <li class="nav-item"> 
                                <a class="nav-link disabled" aria-disabled="true">Disabled</a> 
                            </li> 

                    </ul> 
                </div> 
            </div> 
        </nav> 
    </header> 
    <div> 
        <main role="main" class="pb-3"> 
            @RenderBody() 
        </main> 
    </div> 

    <footer class="border-top footer text-muted"> 
        <div class="container"> 
            &copy; 2024 - WebApplication3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> 
        </div> 
    </footer> 
    <script src="~/lib/jquery/dist/jquery.min.js"></script> 
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> 
    <script src="~/js/site.js" asp-append-version="true"></script> 
    @await RenderSectionAsync("Scripts", required: false) 
</body> 
</html>